name: 'Breaker Analyzer'
description: 'Breaker detects breaking changes in ASP .NET Core APIs and generates IDE warnings for them.'
branding:
  icon: activity
  color: orange
inputs:
  actual:
    description:
      'Path to the actual solution.'
    required: true
  expected:
    description:
      'Path to the expected solution.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '-a'
    - ${{ inputs.actual }}
    - '-e'
    - ${{ inputs.expected }}